# Generated by Django 4.2.7 on 2023-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='никнейм в тг'),
        ),
    ]
