# Generated by Django 4.2.7 on 2023-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_city_user_telegram_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id чата бота'),
        ),
    ]
