# Generated by Django 4.2.7 on 2023-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_habit_action_habit_is_pleasant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_execute',
            field=models.TimeField(verbose_name='время на выполнение привычки'),
        ),
    ]
